### ISSUE TITLE
Unicode Paths don't work

### ISSUE THREAD

**Issue by lyind** [variar/klogg#223]
Both, glogg and klogg do not properly handle unicode paths. If any path segment above the log file, or the log file itself, contain complex unicode characters the file cannot be opened and klogg/glogg starts empty.

The following message is printed on the terminal when opening fails:

```
10:54:14.455 ERROR [56900] [MainWindow::loadFile@1287] Can't open file /home/user/Downloads/some-log/����_�\���m�^�b�`_�^�u���b�glog/blabla.log
```
(The question mark characters are not in the original path and replace unicode characters.)

This is very annoying when analysing log files originating from Japanese, Korean or Chinese systems.

**Comment by variar** [comment]
Thanks for feedback! Does it happen on Linux or Mac? klogg uses [QFile::decodeName](https://doc.qt.io/qt-5/qfile.html#decodeName) to convert paths passed in command line to QString.

**Comment by variar** [comment]
Tried it on my linux box. It seems that russian paths work as expected. Eastern filenames might be more complex. I've changed filename parsing code to allow \0 characters inside names in local encoding. Don't know if it helps.

**Comment by lyind** [comment]
I am also on Linux. I will try to find your fix and quickly test it.

**Comment by lyind** [comment]
The fix is not sufficient, still same result (mangled file name, unicode codepoints replaced with <?> character).

Just in case it matters:
```
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by lyind** [comment]
It seems there is a lot of discussion on the QFile::decodeName() issue:
https://development.qt-project.narkive.com/FHPq4kVJ/deprecating-qfile-encodename-decodename

and a fix for this specific issue we are facing is mentioned in this StackOverflow answer:
https://stackoverflow.com/a/43833340
 
Can you try to set the codec based on environment locale (probably "LC_CTYPE") as described in the StackOverflow answer?

Otherwise I may also prepare a PR if you don't find time to play with this.

**Comment by variar** [comment]
I've added an option to allow user to force decoding filenames as utf-8 strings. This should fix the issue on most systems where Qt can't determine codec for system locale.

Parsing LC_* variables to get correct encoding needs more research. Might need [boost locale](https://www.boost.org/doc/libs/1_74_0/libs/locale/doc/html/classboost_1_1locale_1_1info.html#a1979a5d7b90604c45e856a139c68f5ba) for that.

**Comment by lyind** [comment]
I built with the UTF-8 option included and tested again.

It still doesn't work if the path contains these Japanese characters:

![klogg-still-doesnt-open-logs-at-unicode-paths](https://user-images.githubusercontent.com/18163495/97374925-cea70200-18b9-11eb-9d06-cc696ff6a03d.png)

**Comment by variar** [comment]
It doesn't look like parsing LC_* variable can help in this case. Your `locale` output suggests that UTF-8 is used. However, that "assume utf-8 filenames" option leads to using `QString::fromUtf8` to decode filename, and that does not work for some reason.

I can't reproduce the issue locally. Could you share an example file with the name that causes this problem? Could it be that filename is not in utf-8 encoding?

**Comment by lyind** [comment]
I tested with another (known valid) UTF-8 pathname (Japanese characters) and was open to load the log.

It seems the initial test file path has some invalid UTF-8 characters, even though I get:
```
$ chardetect list
list: utf-8 with confidence 0.99
```

Unfortunately I can't share the actual string as it contains sensitive information.

Wouldn't it be possible to just keep around the path in raw binary form and use that for opening the file? Why even try to decode it? That only seems to make sense for display purposes (showing the path to the user), but not for internal handling.

**Comment by variar** [comment]
Keeping filename in original encoding should work but requires refactoring. Moved this to next release milestone.

**Comment by variar** [comment]
Example of archive path that does not work on windows 2421トレースデータ.zip

**Comment by variar** [comment]
In builds 21.05.0.990+ I've switched to QCommandLineParser. It seems to do right thing most of the time. At least when filename is a valid string in current locale.

Handling paths as byte arrays proved to be difficult, so I'm moving this feature to some future milestone.
