### ISSUE TITLE
[Highlighters]: do not highlight lines excluded from search

### ISSUE THREAD

**Issue by PetbkA** [variar/klogg#658]
**OS**: Windows 10 verison 22H2 x64
**App Version**: 23.07.0.1541 x64 Qt6

It would be nice if highlighters wouldn't [work](https://github.com/variar/klogg/assets/22843816/e5c737f1-5ca5-4626-b3ff-f7078b3aaa90) outside of search zone

**Comment by variar** [comment]
Indeed, excluded lines shouldn't be highlighted

**Comment by variar** [comment]
Fixed in 24.11.0.1662

**Comment by PetbkA** [comment]
**24.11.0.1664-x64-Qt6 on Windows**:
1. Fixed for search limits;
2. Not fixed for certain lines (_Exclude from search_ button)

**Comment by variar** [comment]
Exclude from search button just modifies the main regex and switches it to logical combining mode. Highlighters can't interact with that.
